-- Aqui mostraremos el orden de los modelos/archivos que estan en Roblox Studio los cuales no podemos ver
-- visualmente en el explorador de archivos de VSCode, ya que estos como tal no son archivos .lua normales
-- en este caso, seran archivos como los RemoteEvents, RemoteFunctions, etc.
-- @EstructuraArchivos

--[[

[ReplicatedStorage]
	[Remotes]
		[Events]
			SetTiempo (RemoteEvent)
			IniciarQuiz (RemoteEvent)
			NuevaPregunta (RemoteEvent)
			FinQuiz (RemoteEvent)
		[Functions]
			ObtenerPregunta (RemoteFunction)

]]
